"""

Revision ID: 15c0e3a51d32
Revises: 2c64168ad553
Create Date: 2023-02-13 21:12:23.876107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c0e3a51d32'
down_revision = '2c64168ad553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_detail_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'productdetails', ['product_detail_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_detail_id')

    # ### end Alembic commands ###
