"""coorected rel

Revision ID: 272d8dfd0da8
Revises: 6e421974354b
Create Date: 2023-02-12 11:32:03.623597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '272d8dfd0da8'
down_revision = '6e421974354b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('roles_ibfk_1', type_='foreignkey')
        batch_op.drop_column('users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('roles_ibfk_1', 'roles', ['users'], ['id'])

    # ### end Alembic commands ###
