"""

Revision ID: 2c64168ad553
Revises: b224b197a845
Create Date: 2023-02-13 20:52:44.740558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c64168ad553'
down_revision = 'b224b197a845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productdetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.Column('product_brand', sa.String(length=64), nullable=True),
    sa.Column('product_description', sa.String(length=500), nullable=True),
    sa.Column('product_review', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nick_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['nick_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('city')
        batch_op.drop_column('nick_name')

    op.drop_table('productdetails')
    # ### end Alembic commands ###
