"""

Revision ID: 574aaa122b88
Revises: 76b4148b875a
Create Date: 2023-02-17 00:10:02.257438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '574aaa122b88'
down_revision = '76b4148b875a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_ibfk_5', type_='foreignkey')
        batch_op.drop_column('review_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_ibfk_5', 'productreviews', ['review_id'], ['id'])

    # ### end Alembic commands ###
