"""

Revision ID: 8202a0cf8ff1
Revises: 9ac41a20f215
Create Date: 2023-02-17 13:37:03.037800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8202a0cf8ff1'
down_revision = '9ac41a20f215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productreviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productreviews', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
