"""

Revision ID: 9ac41a20f215
Revises: 574aaa122b88
Create Date: 2023-02-17 12:17:24.467224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ac41a20f215'
down_revision = '574aaa122b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productreviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_review_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'products', ['product_review_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_ibfk_4', type_='foreignkey')
        batch_op.drop_column('product_review_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_review_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('products_ibfk_4', 'productreviews', ['product_review_id'], ['id'])

    with op.batch_alter_table('productreviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_review_id')

    # ### end Alembic commands ###
