"""

Revision ID: aa5a65c91cd7
Revises: 15c0e3a51d32
Create Date: 2023-02-14 16:23:18.037135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5a65c91cd7'
down_revision = '15c0e3a51d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productbrands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_brand', sa.String(length=64), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_brand_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('product_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'producttypes', ['product_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'productbrands', ['product_brand_id'], ['id'])

    with op.batch_alter_table('producttypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producttypes', schema=None) as batch_op:
        batch_op.drop_column('product_type')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_type_id')
        batch_op.drop_column('product_brand_id')

    with op.batch_alter_table('productbrands', schema=None) as batch_op:
        batch_op.drop_column('product_brand')

    # ### end Alembic commands ###
