"""

Revision ID: b0919ebedf4c
Revises: 93da18e1fd91
Create Date: 2023-02-21 20:13:26.717756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0919ebedf4c'
down_revision = '93da18e1fd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
