"""correcte comments

Revision ID: b6f7b57de744
Revises: c4fa404401cc
Create Date: 2023-02-13 17:51:52.499125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f7b57de744'
down_revision = 'c4fa404401cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productbrands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producttypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wishlist', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'wishlists', ['wishlist'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('wishlist')

    op.drop_table('wishlists')
    op.drop_table('producttypes')
    op.drop_table('productbrands')
    # ### end Alembic commands ###
