"""

Revision ID: c1ec0f2c9024
Revises: b0919ebedf4c
Create Date: 2023-02-21 20:17:27.885760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ec0f2c9024'
down_revision = 'b0919ebedf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=64),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
